### ISSUE TITLE
How do I uninstall this?

### ISSUE THREAD

**Issue by SubArrest** [A2-Dev/APPira1n#1]
I installed it, tried it out and decided not to keep it running, how do i uninstall it since now my pi isnt letting me ssh into it and some of my apache websites running simply dont load and timeout once i try to access them online.

**Comment by A2-Dev** [comment]
This was only indended for a headless pi that wasn't running anything else.
I will see about putting in an uninstaller and let you know.

As for the ssh, you have to use ethernet as wifi is being used as access point.

**Comment by SubArrest** [comment]
ah, ok thanks

**Comment by A2-Dev** [comment]
Updated installer and added an uninstall option.
Readme updated as well.
